from tkinter import *
win = Tk()
win.geometry("600x600")
win.title("Calculator")
win.resizable(0,0)
label = Label(win,text = "",width = 20, height = 2, background = "grey")
label.pack()

def interface(win):
    frame = Frame(win)
    frame.pack()
    #  Giao diện:
    b1 = Button(frame,text ="AC", width = 9,bg = "orange",pady=10)
    b1.grid(row = 0, column = 0)
    b2 = Button(frame,text ="+/-", width = 9,background = "orange")
    b2.grid(row = 0, column = 1)
    b3 = Button(frame,text ="%", height = 9, width = 9,background = "orange")
    b3.grid(row = 0, column = 2)
    b4 = Button(frame,text ="/", height = 9, width = 9,background = "orange")
    b4.grid(row = 0, column = 3)
    b5 = Button(frame,text =7, height = 6, width = 9, background = "pink")
    b5.grid(row = 1, column = 0)
    b6 = Button(frame,text =8, height = 6, width = 9,background = "orange")
    b6.grid(row = 1, column = 1)
    b7 = Button(frame,text =9, height = 6, width = 9,background = "orange")
    b7.grid(row = 1, column = 2)
    b8 = Button(frame,text ="x", height = 6, width = 9,background = "pink")
    b8.grid(row = 1, column = 3)
    b9 = Button(frame,text =4, height = 6, width = 9,background = "orange")
    b9.grid(row = 2, column = 0)
    b10 = Button(frame,text =5, height = 6, width = 9,background = "orange")
    b10.grid(row = 2, column = 1)
    b11 = Button(frame,text =6, height = 6, width = 9,background = "orange")
    b11.grid(row = 2, column = 2)
    b12 = Button(frame,text ="-", height = 6, width = 9,background = "pink")
    b12.grid(row = 2, column = 3)
    b13 = Button(frame,text =1, height = 6, width = 9,background = "pink")
    b13.grid(row = 3, column = 0)
    b14 = Button(frame,text =2, height = 6, width = 9,background = "pink")
    b14.grid(row = 3, column = 1)
    b15 = Button(frame,text =3, height = 6, width = 9,background = "pink")
    b15.grid(row = 3, column = 2)
    b16 = Button(frame,text ="+", height = 6, width = 9,background = "pink")
    b16.grid(row = 3, column = 3)
    b17 = Button(frame,text =0, height = 6, width = 18,background = "pink")
    b17.grid(row = 4, columnspan = 2)
    b18 = Button(frame,text =".", height = 6, width = 9,background = "pink")
    b18.grid(row = 4, column = 2)
    b19 = Button(frame,text ="=", height = 6, width = 9,background = "pink")
    b19.grid(row = 4, column = 3)

interface(win)

mainloop()